/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Desktop;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author VINICIO
 */
public class Facturacion extends javax.swing.JFrame {

    private final VentanaCrudClientes ventanaCrudClientes;
    private final VentanaCrudEmpleados ventanaCrudEmpleados;
    private  ventanaOrden ventanaOrden;
    private final VentanaTiposTrabajos tiposTrabajos;
    private VentanaCrudProducto ventanaCrudProducto;
    private VentanaCrudFactura ventanaCrudFactura;
    private VentanaIngresoProducto ventanaIngresoProducto;
//    
//    
//    private ventanaCrudProveedor ventanaCrudProveedor;
//    
//    
//    
//    private VentanaPedidos ventanaPedidos;
//    private VentanaKardex ventanaKardex;
    private final boolean bandera = true;

    public Facturacion() {

        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        ventanaCrudClientes = new VentanaCrudClientes(btnClientes);
        ventanaCrudEmpleados = new VentanaCrudEmpleados(btnEmpleados);
        ventanaOrden = new ventanaOrden(btnOrden);
        tiposTrabajos = new VentanaTiposTrabajos(btnTipTrabajos);
        ventanaCrudProducto = new VentanaCrudProducto(btnProducto);
        ventanaCrudFactura = new VentanaCrudFactura(btnFactura);
        ventanaIngresoProducto = new VentanaIngresoProducto(btnIngreso);

         escritorio.setFocusable(false);
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        btnClientes = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnOrden = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        btnIngreso = new javax.swing.JButton();
        btnTipTrabajos = new javax.swing.JButton();
        btnIngreso3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto1.png"))); // NOI18N
        btnProducto.setText("PRODUCTO");
        btnProducto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProducto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnOrden.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden.png"))); // NOI18N
        btnOrden.setText("ORDEN DE TRABAJO");
        btnOrden.setHideActionText(true);
        btnOrden.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrden.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenActionPerformed(evt);
            }
        });

        btnEmpleados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N
        btnEmpleados.setText("EMPLEADOS");
        btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pedidos.png"))); // NOI18N
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        btnFactura.setText("FACTURACION");
        btnFactura.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnFactura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFactura.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFactura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        btnIngreso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresoProducto.png"))); // NOI18N
        btnIngreso.setText("INGRESO");
        btnIngreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngreso.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnIngreso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });

        btnTipTrabajos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTipTrabajos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipT.png"))); // NOI18N
        btnTipTrabajos.setText("TIPOS DE TRABAJO");
        btnTipTrabajos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTipTrabajos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTipTrabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipTrabajosActionPerformed(evt);
            }
        });

        btnIngreso3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ayuda.png"))); // NOI18N
        btnIngreso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreso3ActionPerformed(evt);
            }
        });

        escritorio.setLayer(btnClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnOrden, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnEmpleados, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnPedidos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnFactura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnIngreso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnTipTrabajos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnIngreso3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClientes)
                    .addComponent(btnIngreso)
                    .addComponent(btnTipTrabajos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIngreso3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 108, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProducto)
                    .addComponent(btnClientes)
                    .addComponent(btnOrden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPedidos)
                        .addComponent(btnIngreso))
                    .addComponent(btnFactura, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEmpleados)
                    .addComponent(btnTipTrabajos)
                    .addComponent(btnIngreso3))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void finalize() throws Throwable {
        System.out.println("finalzado");
    }

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed

        if (ventanaCrudClientes.isShowing() != true) {
            btnClientes.setEnabled(false);
            escritorio.add(ventanaCrudClientes);

            Dimension desktopSize = this.getSize();
            Dimension FrameSize = ventanaCrudClientes.getSize();
            ventanaCrudClientes.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

            ventanaCrudClientes.setVisible(true);
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        if (ventanaCrudProducto.isShowing() != true) {

            btnProducto.setEnabled(false);
            escritorio.add(ventanaCrudProducto);
            Dimension desktopSize = this.getSize();
            Dimension FrameSize = ventanaCrudProducto.getSize();
            ventanaCrudProducto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            ventanaCrudProducto.setVisible(true);
        }
        
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenActionPerformed
        if (ventanaOrden.isShowing() != true) {
            ventanaOrden = new ventanaOrden(btnOrden);
            btnOrden.setEnabled(false);
            escritorio.add(ventanaOrden);
            ventanaOrden.setVisible(true);
        }
    }//GEN-LAST:event_btnOrdenActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        if (ventanaCrudEmpleados.isShowing() != true) {
            btnEmpleados.setEnabled(false);
            escritorio.add(ventanaCrudEmpleados);

            Dimension desktopSize = this.getSize();
            Dimension FrameSize = ventanaCrudEmpleados.getSize();
            ventanaCrudEmpleados.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

            ventanaCrudEmpleados.setVisible(true);
        }
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
//        if (ventanaPedidos.isShowing() != true) {
//
//            btnPedidos.setEnabled(false);
//            escritorio.add(ventanaPedidos);
//            ventanaPedidos.setVisible(true);
//        }
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        if (ventanaCrudFactura.isShowing() != true) {

            btnFactura.setEnabled(false);
            ventanaCrudFactura = new VentanaCrudFactura(btnFactura);
            
            escritorio.add(ventanaCrudFactura);
            Dimension desktopSize = this.getSize();
            Dimension FrameSize = ventanaCrudFactura.getSize();
            ventanaCrudFactura.setLocation((desktopSize.width - FrameSize.width) / 2, ((desktopSize.height - FrameSize.height) / 2)-50);

            ventanaCrudFactura.setVisible(true);
        }
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        if (ventanaIngresoProducto.isShowing() != true) {

            btnIngreso.setEnabled(false);
            Dimension desktopSize = this.getSize();
            Dimension FrameSize = ventanaIngresoProducto.getSize();
            ventanaIngresoProducto.setLocation((desktopSize.width - FrameSize.width) / 2, ((desktopSize.height - FrameSize.height) / 2)-50);

            escritorio.add(ventanaIngresoProducto);
            ventanaIngresoProducto.setVisible(true);
        }
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void btnTipTrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipTrabajosActionPerformed
        if (tiposTrabajos.isShowing() != true) {

            btnTipTrabajos.setEnabled(false);
            escritorio.add(tiposTrabajos);
            tiposTrabajos.setVisible(true);
        }
    }//GEN-LAST:event_btnTipTrabajosActionPerformed

    private void btnIngreso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreso3ActionPerformed
        try {
            File path = new File("AyudaSistemaDeFacturacionn.pdf");
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnIngreso3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnIngreso3;
    private javax.swing.JButton btnOrden;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnTipTrabajos;
    private javax.swing.JDesktopPane escritorio;
    // End of variables declaration//GEN-END:variables

}
