/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controladores.ControladorCliente;
import controladores.ControladorDetalle;
import controladores.ControladorFactura;
import controladores.ControladorProducto;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import modelo.Cliente;
import modelo.Detalle;
import modelo.Factura;
import modelo.Producto;

/**
 *
 * @author VINICIO
 */
public class VentanaCrudFactura extends javax.swing.JInternalFrame {

    private DefaultTableModel modelotabla;
    private DefaultComboBoxModel modeloCombo;
    private DefaultComboBoxModel modeloCombo2;
    private DefaultComboBoxModel modeloCombo3;
    private GregorianCalendar fecha;
    private SimpleDateFormat formatoFecha;
    private JButton b;
    private ControladorProducto controladorProducto;
    private ControladorCliente controladorCliente;
    private ControladorFactura controladorFactura;
    private ControladorDetalle controladorDetalle;

    public VentanaCrudFactura(JButton b) {
        initComponents();
        this.b = b;
        modelotabla = new DefaultTableModel();
        fecha = new GregorianCalendar();

        formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        Date f = fecha.getTime();
        String fech = formatoFecha.format(f);

        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        txtFecha.setText(dateFormat.format(date));

        controladorProducto = new ControladorProducto();
        controladorCliente = new ControladorCliente();
        controladorFactura = new ControladorFactura();
        controladorDetalle = new ControladorDetalle();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jLabel25 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTotalFactura = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboIva = new javax.swing.JComboBox<>();
        txtIVA = new javax.swing.JTextField();
        btnGuardarFactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNotas = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtVuelto = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFacturas = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaDetallexCliente = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("CRUD Factura");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                cerrando(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Sitka Heading", 2, 24)); // NOI18N
        jLabel25.setText("CONTROLADOR FACTURA");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, 277, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/factura1.png"))); // NOI18N
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 80, -1));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTotalFactura.setEnabled(false);

        txtSubtotal.setEnabled(false);

        jLabel12.setText("SUBTOTAL");

        jLabel14.setText("TOTAL A PAGAR");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        comboIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IVA 12%", "IVA 0%" }));
        comboIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIvaActionPerformed(evt);
            }
        });

        txtIVA.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboIva, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIVA)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(txtSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnGuardarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/guardar.png"))); // NOI18N
        btnGuardarFactura.setText("GUARDAR FACTURA");
        btnGuardarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFacturaActionPerformed(evt);
            }
        });

        tablaDetalle.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, ""}
            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD", "PRECIO", "SUBTOTAL"
            }
        ));
        tablaDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaDetalleMousePressed(evt);
            }
        });
        tablaDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaDetalleKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablaDetalle);

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("DETALLE");

        jLabel5.setFont(new java.awt.Font("Sitka Display", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("FACTURA");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("C.I:");

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("DIRECCION: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("TELEFONO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("CLIENTE: ");

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CORREO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("FECHA :");

        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });

        jButton1.setText("Consumidor Final");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCedula))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtCorreo)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton1)))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("NOTAS DEL PAGO:");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtVuelto.setEnabled(false);

        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSaldoKeyPressed(evt);
            }
        });

        jLabel23.setText("CUANTO:");

        jLabel31.setText("VUELTO:");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnGuardarFactura)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNotas))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnGuardarFactura))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CREAR", jPanel1);

        tablaFacturas.setBackground(new java.awt.Color(102, 255, 255));
        tablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro. FACTURA", "CLIENTE", "TOTAL", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaFacturas);

        tablaDetallexCliente.setBackground(new java.awt.Color(204, 255, 204));
        tablaDetallexCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "CANTIDAD", "DESCRIPCION", "PRECIO", "SUBTOTAL"
            }
        ));
        tablaDetallexCliente.setEnabled(false);
        jScrollPane6.setViewportView(tablaDetallexCliente);

        jLabel24.setFont(new java.awt.Font("Sitka Display", 3, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 255));
        jLabel24.setText("LISTA DE FACTURAS");

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresor.jpg"))); // NOI18N
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("LISTAR", jPanel9);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 680, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrando(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_cerrando
        b.setEnabled(true);
    }//GEN-LAST:event_cerrando

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        int x = jTabbedPane1.getSelectedIndex();

        if (x == 1) {
            ArrayList<Factura> lista = new ArrayList<>();
            lista = controladorFactura.listar();
            if (lista.isEmpty()) {
                modelotabla.setRowCount(0);
                JOptionPane.showMessageDialog(null, "Lista de clientes vacia");

            } else {
                modelotabla = new DefaultTableModel();
                Object[] datoscliente;
                modelotabla.addColumn("CODIGO");
                modelotabla.addColumn("CLIENTE");
                modelotabla.addColumn("SUBTOTAL");
                modelotabla.addColumn("IVA");
                modelotabla.addColumn("TOTAL");
                modelotabla.addColumn("NOTAS");
                modelotabla.addColumn("FECHA");

                tablaFacturas.setModel(modelotabla);

                for (int i = 0; i < lista.size(); i++) {
                    datoscliente = new Object[7];
                    Factura f = lista.get(i);
                    datoscliente[0] = f.getCodigo();
                    datoscliente[1] = f.getCliente().getNombre() + " " + f.getCliente().getApellido();
                    datoscliente[2] = f.getSubtotal();
                    datoscliente[3] = f.getIva();
                    datoscliente[4] = f.getTotal();
                    datoscliente[5] = f.getNotas();
                    datoscliente[6] = f.getFecha();
                    modelotabla.addRow(datoscliente);

                }
                tablaFacturas.setModel(modelotabla);
                TableColumnModel columnModel = tablaFacturas.getColumnModel();
                columnModel.getColumn(0).setPreferredWidth(3);
                columnModel.getColumn(1).setPreferredWidth(200);
                columnModel.getColumn(2).setPreferredWidth(50);
                columnModel.getColumn(3).setPreferredWidth(50);
                columnModel.getColumn(4).setPreferredWidth(50);

            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void tablaFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFacturasMouseClicked
        int row = tablaFacturas.getSelectedRow();
        int cod = (int) tablaFacturas.getValueAt(row, 0);

        ArrayList<Detalle> lista = new ArrayList<>();
        lista = controladorDetalle.listar(cod);
        if (lista.isEmpty()) {
            modelotabla.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Lista DETALLE vacia");

        } else {
            modelotabla = new DefaultTableModel();
            Object[] datoscliente;
            modelotabla.addColumn("CODIGO");
            modelotabla.addColumn("PRODUCTO");
            modelotabla.addColumn("CANTIDAD");
            modelotabla.addColumn("PRECIO");
            modelotabla.addColumn("SUBTOTAL");

            tablaDetallexCliente.setModel(modelotabla);

            for (int i = 0; i < lista.size(); i++) {
                datoscliente = new Object[5];
                Detalle d = lista.get(i);
                Producto p = controladorProducto.buscarID(d.getProducto() + "");
                datoscliente[0] = d.getCodigo();
                datoscliente[1] = p.getNombre();
                datoscliente[2] = d.getCantidad();
                datoscliente[3] = p.getPrecio();
                datoscliente[4] = p.getPrecio() * d.getCantidad();

                modelotabla.addRow(datoscliente);

            }
            tablaDetallexCliente.setModel(modelotabla);
            TableColumnModel columnModel = tablaDetallexCliente.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(3);
        }
    }//GEN-LAST:event_tablaFacturasMouseClicked

    private void txtSaldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                double saldo = Double.parseDouble(txtSaldo.getText());
                double total = Double.parseDouble(txtTotalFactura.getText());
                double res = saldo - total;
                DecimalFormat df = new DecimalFormat("#.00");

                txtVuelto.setText(String.valueOf(df.format(res)));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_txtSaldoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cliente c = controladorCliente.buscar("9999999999999");
        if (c != null) {
            txtCedula.setText(c.getCedula());
            txtCliente.setText(c.getNombre() + " " + c.getApellido());
            txtTelefono.setText(c.getTelefono());
            txtDireccion.setText(c.getDireccion());
            txtCorreo.setText(c.getCorreo());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaKeyTyped

    private void txtFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaKeyReleased

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaKeyPressed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
        } else if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
            txtCedula.setBackground(Color.RED);
        } else {
            txtCedula.setBackground(Color.CYAN);
            if (txtCedula.getText().length() == 13) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        if (txtCedula.getText().length() == 10) {
            if (controladorCliente.IdentificadorCedula(txtCedula.getText()) == true) {
                txtCedula.setBackground(Color.GREEN);
            } else {
                txtCedula.setBackground(Color.red);
            }
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtCedula.getText().equals("")) {
                Cliente c = controladorCliente.buscar(txtCedula.getText());
                if (c != null) {
                    txtCliente.setText(c.getNombre() + " " + c.getApellido());
                    txtTelefono.setText(c.getTelefono());
                    txtDireccion.setText(c.getDireccion());
                    txtCorreo.setText(c.getCorreo());
                } else {
                    JOptionPane.showMessageDialog(this, "CLIENTE NO ENCONTRADO", "CLIENTE", JOptionPane.INFORMATION_MESSAGE);
                    txtCedula.setText("");
                    txtCliente.setText("");
                    txtTelefono.setText("");
                    txtDireccion.setText("");
                    txtCorreo.setText("");

                    txtCliente.setEditable(false);
                    txtTelefono.setEditable(false);
                    txtDireccion.setEditable(false);
                    txtCorreo.setEditable(false);

                    txtCedula.setBackground(Color.WHITE);
                    txtCliente.setBackground(Color.WHITE);
                    txtTelefono.setBackground(Color.WHITE);
                    txtDireccion.setBackground(Color.WHITE);
                    txtCorreo.setBackground(Color.WHITE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "DATOS INGRESADOS INCORRECTOS", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtCedula.setText("");
                txtCliente.setText("");
                txtTelefono.setText("");
                txtDireccion.setText("");
                txtCorreo.setText("");

                txtCliente.setEditable(false);
                txtTelefono.setEditable(false);
                txtDireccion.setEditable(false);
                txtCorreo.setEditable(false);

                txtCedula.setBackground(Color.WHITE);
                txtCliente.setBackground(Color.WHITE);
                txtTelefono.setBackground(Color.WHITE);
                txtDireccion.setBackground(Color.WHITE);
                txtCorreo.setBackground(Color.WHITE);
            }
        }
    }//GEN-LAST:event_txtCedulaKeyPressed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void tablaDetalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaDetalleKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {

            String codigo = tablaDetalle.getValueAt(tablaDetalle.getSelectedRow(), 0) + "";
            Producto c = controladorProducto.buscar(codigo);
            if (c != null) {
                if (c.getStock() > 0) {
                    int numero = 0;
                    boolean bandera = false;
                    tablaDetalle.setValueAt(c.getNombre(), tablaDetalle.getSelectedRow(), 1);

                    do {
                        try {
                            numero = Integer.parseInt(javax.swing.JOptionPane.showInputDialog("Ingrese Cantidad en " + c.getMedida()
                                    + "\n Existen: " + c.getStock() + " " + c.getMedida()));
                            if (numero <= c.getStock()) {
                                bandera = true;
                            } else {
                                javax.swing.JOptionPane.showMessageDialog(this, "INGRES UNA CANTIDAD MENOR A: " + c.getStock());
                            }
                        } catch (NumberFormatException e) {
                            javax.swing.JOptionPane.showMessageDialog(this, "Solo se permiten numeros");
                            bandera = false;
                        }
                    } while (!bandera);
                    int cant = numero;
                    tablaDetalle.setValueAt(cant, tablaDetalle.getSelectedRow(), 2);

                    tablaDetalle.setValueAt(c.getPrecio(), tablaDetalle.getSelectedRow(), 3);
                    tablaDetalle.setValueAt(cant * c.getPrecio(), tablaDetalle.getSelectedRow(), 4);
                    double subtotal = 0;
                    for (int i = 0; i < tablaDetalle.getRowCount(); i++) {

                        if (tablaDetalle.getValueAt(i, 4).toString().length() > 0) {

                            subtotal = subtotal + (double) tablaDetalle.getValueAt(i, 4);
                            txtSubtotal.setText(subtotal + "");
                        }
                    }

                    modelotabla = (DefaultTableModel) tablaDetalle.getModel();
                    modelotabla.addRow(new Object[]{"", "", "", "", ""});
                    tablaDetalle.setModel(modelotabla);
                    double iva = subtotal * 0.12;
                    if (comboIva.getSelectedIndex() == 1) {
                        iva = 0;
                    }
                    txtIVA.setText(iva + "");
                    double total = iva + subtotal;
                    txtTotalFactura.setText(total + "");

                } else {
                    JOptionPane.showMessageDialog(this, "Ya no existen productos: Por favor ingrese mas " + c.getMedida());
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se a encontrado el producto");
            }
        }
    }//GEN-LAST:event_tablaDetalleKeyReleased

    private void tablaDetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDetalleMousePressed
        if ((evt.getModifiers() & 4) != 0) {
            int x = JOptionPane.showConfirmDialog(this, "Desea quitar producto");
            if (x == JOptionPane.OK_OPTION) {
                modelotabla = (DefaultTableModel) tablaDetalle.getModel();
                modelotabla.removeRow(tablaDetalle.getSelectedRow());
                tablaDetalle.setModel(modelotabla);
                double subtotal = 0;
                txtSubtotal.setText("0.0");
                for (int i = 0; i < tablaDetalle.getRowCount(); i++) {
                    if (tablaDetalle.getValueAt(i, 4).toString().length() > 0) {
                        subtotal = subtotal + (double) tablaDetalle.getValueAt(i, 4);
                        txtSubtotal.setText(subtotal + "");
                    }
                }
                double iva = subtotal * 0.12;
                if (comboIva.getSelectedIndex() == 1) {
                    iva = 0;
                }
                txtIVA.setText(iva + "");
                double total = iva + subtotal;
                txtTotalFactura.setText(total + "");
            }
        }
    }//GEN-LAST:event_tablaDetalleMousePressed

    private void btnGuardarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFacturaActionPerformed
        int cont = 0;
        String mensaje = "";
        if (!txtCedula.getText().equals("")) {
            cont++;
        } else {
            mensaje = "Falta cliente";
        };
        if (tablaDetalle.getRowCount() - 1 >= 1) {
            cont++;
        } else {
            mensaje = "Falta productos";
        };

        if (cont == 2) {
            Factura f = new Factura();
            f.setCodigo(controladorFactura.obtenerCodigo());
            f.setCliente(controladorCliente.buscar(txtCedula.getText()));
            f.setSubtotal(Double.parseDouble(txtSubtotal.getText()));
            f.setIva(Double.parseDouble(txtIVA.getText()));
            f.setTotal(Double.parseDouble(txtTotalFactura.getText()));
            f.setNotas(txtNotas.getText() + " ");
            f.setFecha(txtFecha.getText());
            boolean op = controladorFactura.crear(f);
            if (op) {
                for (int i = 0; i < tablaDetalle.getRowCount(); i++) {
                    if (tablaDetalle.getValueAt(i, 4).toString().length() > 0) {
                        Detalle d = new Detalle();
                        d.setCodigo(controladorDetalle.obtenerCodigo());
                        String codigo = String.valueOf(tablaDetalle.getValueAt(i, 0));
                        d.setProducto(controladorProducto.buscar(codigo).getId());

                        int cant = Integer.parseInt(tablaDetalle.getValueAt(i, 2).toString());
                        d.setCantidad(cant);
                        d.setFactura(f.getCodigo());
                        controladorDetalle.crear(d);
                        controladorProducto.disminuir(codigo, cant);
                    }
                }
                int impr = JOptionPane.showConfirmDialog(this, "Desea imprmir");
                if (impr == JOptionPane.OK_OPTION) {
                    controladorFactura.impirmir(f.getCodigo());
                } else {
                    JOptionPane.showMessageDialog(this, "Podras Imprimir Cuando Listes");
                }

                Date date = new Date();
                DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                txtFecha.setText(dateFormat.format(date));
                txtCedula.setText("");
                txtSubtotal.setText("");
                txtIVA.setText("");
                txtTotalFactura.setText("");
                txtNotas.setText("");
                txtCedula.setText("");
                txtCliente.setText("");
                txtTelefono.setText("");
                txtDireccion.setText("");
                txtCorreo.setText("");

                modelotabla = null;
                modelotabla = (DefaultTableModel) tablaDetalle.getModel();
                while (modelotabla.getRowCount() > 0) {
                    for (int j = 0; j < modelotabla.getRowCount(); j++) {
                        modelotabla.removeRow(j);
                    }
                }
                modelotabla.addRow(new Object[]{"", "", "", "", ""});
                tablaDetalle.setModel(modelotabla);

            } else {
                JOptionPane.showMessageDialog(this, "Erro con la base");
            }

        } else {
            JOptionPane.showMessageDialog(this, mensaje);

        }
    }//GEN-LAST:event_btnGuardarFacturaActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        int row = tablaFacturas.getSelectedRow();
        int cod = (int) tablaFacturas.getValueAt(row, 0);
        controladorFactura.impirmir(cod);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void comboIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIvaActionPerformed
        double subtotal = 0;
        for (int i = 0; i < tablaDetalle.getRowCount(); i++) {
            if (tablaDetalle.getValueAt(i, 4).toString().length() > 0) {
                subtotal = subtotal + (double) tablaDetalle.getValueAt(i, 4);
                txtSubtotal.setText(subtotal + "");
            }
        }
        double iva = subtotal * 0.12;
        if (comboIva.getSelectedIndex() == 1) {
            iva = 0;
        }
        txtIVA.setText(iva + "");
        double total = iva + subtotal;
        txtTotalFactura.setText(total + "");
    }//GEN-LAST:event_comboIvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarFactura;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> comboIva;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTable tablaDetallexCliente;
    private javax.swing.JTable tablaFacturas;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtNotas;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotalFactura;
    private javax.swing.JTextField txtVuelto;
    // End of variables declaration//GEN-END:variables
}
